---
title: "Grades by Demographics"
author: "Chad E. Brassil, Faculty Director of Undergraduate Analytics"
date: "December 2023, edited 4/25/24"
output:
  rmdformats::readthedown
---

```{css, echo=FALSE}
.gt_table {
  float:left;
}
```

```{r, include=FALSE}
# Installs required packages if they are not already installed
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("gt")) install.packages("gt")
if (!require("ggiraph")) install.packages("ggiraph")
if (!require("scales")) install.packages("scales")
```

```{r libraries, include=FALSE, message = FALSE}
#Load libraries and data

#The default will be to look for data_sim.csv file in the same folder in which you have this R file. If you format your own institutional data similar to the data_sim.csv #file, the code should work on your institutional data as well.

library(tidyverse)
library(gt)
ds <- read_csv("data_sim.csv")
```



```{r, include=FALSE}
# Add acceptable column names here:
courseColumns <- c("course","Course","class","Class")
termColumns <- c("term","Term","AMIS","Amis_Term_Code")
gradeColumns <- c("grade","Grade","Letter_Grade","letter_grade")
semesterColumns <- c("semester","Semester","year_and_semester","Year_and_Semester")

# Check for "course"
columnNames <- colnames(ds)
hasCourseCol <- any(courseColumns %in% columnNames)
if (hasCourseCol){
   print("course column found")
} else {
   stop("course column not found") }

# Check for "term"
hasTermCol <- any(termColumns %in% columnNames)
if (hasTermCol){
   print("term column found") 
} else {
   stop("term column not found") }

# Check for "grade"
hasGradeCol <- any(gradeColumns %in% columnNames)
if (hasGradeCol){
   print("grade column found") 
} else {
   stop("grade column not found") }

# Check for "semester"
hasSemesterCol <- any(semesterColumns %in% columnNames)
if (hasSemesterCol){
   print("semester column found") 
} else {
   stop("semester column not found") }
```

```{r, echo=FALSE}
# Isolate demographic columns
demographicCols <- c()

for (col in columnNames) {
  if (!(col %in% courseColumns || col %in% termColumns || col %in% gradeColumns || col %in% semesterColumns)) {
    demographicCols <- c(demographicCols, col)
  }
}
```

```{r, include=FALSE}
## Data Cleaning
# Add a grade_point and a DFW column to the data
ds %>%
  mutate(grade_point = case_when(
    grade == "A+" ~ 4.0,
    grade == "A" ~ 4.0,
    grade == "A-" ~ 3.67,
    grade == "B+" ~ 3.33,
    grade == "B" ~ 3.0,
    grade == "B-" ~ 2.67,
    grade == "C+" ~ 2.33,
    grade == "C" ~ 2.0,
    grade == "C-" ~ 1.67,
    grade == "D+" ~ 1.33,
    grade == "D" ~ 1.0,
    grade == "D-" ~ 0.67,
    grade == "F" ~ 0.0,
    TRUE ~ NaN)) %>%
  mutate(ABCDFW = case_when(
    grade %in% c("A+","A","A-","B+","B","B-","C+","C","C-") ~ "ABC",
    grade %in% c("D+","D","D-","F","W") ~ "DFW",
    TRUE ~ NA)) -> dt
```


```{r, include = FALSE}
# Isolates one course as d1
# Change input course here to generate differing reports (Chem1 or Calc1):
inputCourse <- "Calc1"
dt %>%
  filter(course == as.character(inputCourse)) -> d1

```


```{r, results='asis', echo=FALSE}
# Threshold Number of Students or Fewer Check for Privacy - Change threshold value here:
threshold <- 5
# Aggregate columns that violate privacy concerns, removed from output
keptCols <- c()
droppedCols <- c()

for (i in demographicCols) {
  counts <- d1 %>%
  count(!!sym(i))
  
  if(any(counts$n < threshold)) {
    droppedCols <- c(droppedCols, i)
  }
  else {
    keptCols <- c(keptCols, i)
  }
}

if (length(droppedCols) != 0) {
  #Prints names of removed columns
  cat("Removed for privacy:",droppedCols)
}
```

# DFW Rates for `r d1$course[1]`
#### The number of students in each category is listed under the percentage.

```{r, results='asis', echo=FALSE, include=TRUE}
# Generate a table for each demographic category included
for (i in keptCols) {
  d1 %>%
  group_by(course, !!sym(i)) %>%
  summarize(students=n(), .groups = "drop" ) %>%
  pivot_wider(names_from = !!i, values_from=students) %>%
  mutate(Gap = " ", demCat = " ") %>%
  relocate(Gap, .after = "course") %>%
  relocate(demCat, .after = "Gap") %>%
  select(-course) -> numStudents # Generates a row with the number of students in each category
  
d1 %>%
  group_by(course, !!sym(i)) %>%
  summarize(DFW = sum(ABCDFW == "DFW")/n(), .groups = "drop" ) %>%
  pivot_wider(names_from = !!i, values_from=DFW) %>%
  # Calculates gap percentage and then converts to character type
  mutate(Gap = max(across(!matches("course"))) - min(across(!matches("course")))) %>%
  mutate(Gap = format(round(Gap * 100, digits = 1), nsmall = 1)) %>%
  mutate(Gap = as.character(Gap)) %>%
  mutate(Gap = paste0(Gap,'%')) %>%
  relocate(Gap, .after = "course") %>%
  select(-course) %>%
  mutate(demCat = i) %>% 
  relocate(demCat, .after = "Gap") %>% 
  #Row binds numStudents, the number of students in each category
  rbind(numStudents) %>%
  # Table creation starts here
  gt(rowname_col="demCat") %>%
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_body(columns = c(Gap))) %>%
  fmt_percent(decimals = 1, rows = 1) -> table

# Code to generate the interactive visualization to go with each table
d1 %>%
  group_by(course, !!sym(i)) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), students = n(), DFW_students=sum(ABCDFW == "DFW"), .groups = "drop" ) %>%
  group_by(course) %>%
  mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
  
  
  # Sets scale of x-axis to 50% or highest Max + 10%
  mutate(students_in_gap = students[which.max(DFW)]*(max(DFW)-min(DFW)), diversity = students/sum(students), total_enrollment =      sum(students) ) -> b4maxCheck
if (b4maxCheck$DFW_max[1] > 0.5) {
  upperLimit <- b4maxCheck$DFW_max[1] + 0.1 
} else {
    upperLimit <- 0.5
    }

# sorts by number of students in each category for factoring purposes
  b4maxCheck %>%
  arrange(desc(students)) -> sorted_d1
  sorted_d1 %>%
    pull(!!sym(i)) -> cat_sorted
  sorted_d1 %>%
  mutate(cat_factors = factor(!!sym(i), levels = cat_sorted)) %>%
    
# Interactive plotting code starts here:
  ggplot(aes(x = DFW, y = course, fill = cat_factors)) +
  theme_classic() +
  geom_segment_interactive(aes(x = DFW_min, xend = DFW_max, yend=course, tooltip = paste(
    course,"\r",
    !!sym(i),"\r",
    "Percentage Points Gap:",percent(DFW_max - DFW_min, accuracy = 0.1),"\r",
    "Grade Ratio:",round(DFW_max/DFW_min, digits = 2),"\r",
    "Students in Gap:",round(students_in_gap, digits = 1),"\r",
    "Total Enrollments:",total_enrollment,"\r"
    )), colour = "gray", linewidth = 15) +
  scale_size(range = c(5,15), guide = "none") +
  geom_point_interactive(aes(size = students, tooltip = paste0(
    course,"\r",
    !!sym(i)," (",percent(diversity,accuracy = 0.1)," of students)\r",
    DFW_students," of ",students," enrollments\r",
    percent(DFW, accuracy = 0.1)," DFW" )) , shape = 21) +
  scale_x_continuous(labels = scales::percent, limits = c(0,upperLimit)) +
  guides(fill = guide_legend(override.aes = list(size = 10), title="")) +
  labs(fill = sym(i), y = "") -> plot
  
# Title created in markdown
cat('\n##', i , '\n')

print(htmltools::tagList(girafe(ggobj = plot))) # Use htmltools::tagList() to generate multiple interactive plots
                                                # results = 'asis' must go in {}
print(table)
}
```

<br><br><br><br><br>

# Intersectionality Data for `r d1$course[1]`
#### The number of students in each category is listed under the percentage.

```{r, results='asis', echo=FALSE, warning=FALSE}
# Aggregate columns that violate privacy concerns, removed from output
keptColsInt <- c()
droppedColsInt <- c()

# Loops through all combinations of demographic columns
for (i in combn(demographicCols,2,simplify=FALSE)) {

    countsInt <- d1 %>%
    group_by(course,!!sym(i[1]),!!sym(i[2])) %>%
    summarize(students=n(), .groups = "drop" )
  
  if(any(countsInt$students < threshold)) {
    droppedColsInt <- c(droppedColsInt, i)
  }
  else {
    keptColsInt <- c(keptColsInt, i)
  }
}

if (length(droppedColsInt) != 0) {
  #Formats dropped columns to look nice in the report
  formattedPairs <- ""
  for (j in seq(1, length(droppedColsInt), by = 2)) {
    formattedPairs <- paste(formattedPairs, droppedColsInt[j], sep = "")
    if (j + 1 <= length(droppedColsInt)) {
      formattedPairs <- paste(formattedPairs, " & ", droppedColsInt[j + 1], sep = "")
    }
    formattedPairs <- paste(formattedPairs, ", ", sep = "")
  }
  formattedPairs <- sub(", $", "", formattedPairs)
  
  cat("Removed for privacy:", formattedPairs)
}
```

```{r, results = 'asis', echo=FALSE, include=TRUE, warning = FALSE}
# Loops through all possible pairs of columns that have passed the privacy check
for (i in seq(from = 1, to = length(keptColsInt), by=2)) {
  # One pair of categories to work with:
  pair <- c(keptColsInt[i], keptColsInt[i+1]) 

d1 %>%
    group_by(course, !!sym(pair[1]), !!sym(pair[2])) %>%
    summarize(students=n(), .groups = "drop" ) %>%
    pivot_wider(names_from = c(!!sym(pair[1]), !!sym(pair[2])), values_from=students) %>%
    mutate(Gap = " ", demCat = " ") %>%
    relocate(Gap, .after = "course") %>%
    relocate(demCat, .after = "Gap") %>%
    select(-course) -> numStudentsInt   # Creates the row with number of students in each category to use later

  d1 %>%
    group_by(course,!!sym(pair[1]),!!sym(pair[2])) %>%
    summarize( DFW = sum(ABCDFW == "DFW")/n(), .groups = "drop" ) %>%
    pivot_wider(names_from = c(!!pair[1],!!pair[2]), values_from=DFW) %>%
    # Calculates the gap percentage and converts it to character type
    mutate(Gap = max(across(!matches("course"))) - min(across(!matches("course")))) %>%
    mutate(Gap = format(round(Gap * 100, digits = 1), nsmall = 1)) %>%
    mutate(Gap = as.character(Gap)) %>%
    mutate(Gap = paste0(Gap,'%')) %>%
    relocate(Gap, .after = "course") %>%
    select(-course) %>%
    mutate(demCat = paste(!!pair[1], "&", !!pair[2]) ) -> titlePull  # pulls the title to use later
  
  titlePull %>%
    rbind(numStudentsInt) %>%    # adds in row with number of students in each category
    
    #Table creation starts here:
    gt(rowname_col="demCat") %>%
    fmt_percent( 
    decimals = 1, rows=1
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = Gap)) %>%
  tab_spanner_delim(delim="_") -> table
  
#Code for interactive visualization starts here
  pair <- c(keptColsInt[i], keptColsInt[i+1]) 
  #Pulls title to use later
  pairTitle <- paste(keptColsInt[i],"&",keptColsInt[i+1])
d1 %>%
    group_by(course, !!sym(pair[1]), !!sym(pair[2])) %>%
    summarize(DFW = sum(ABCDFW == "DFW")/n(), students=n(), DFW_students=sum(ABCDFW == "DFW"), .groups = "drop" ) %>%
    mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
  #Creates labels for each category of intersection
    mutate(intersection = paste(!!sym(pair[1]),!!sym(pair[2]), sep = "-")) %>%
  mutate(students_in_gap = students[which.max(DFW)]*(max(DFW)-min(DFW)), diversity = students/sum(students), total_enrollment =      sum(students) ) -> b4maxCheck
# Sets scale of x-axis to 50% or highest Max + 10%
if (b4maxCheck$DFW_max[1] > 0.5) {
  upperLimit <- b4maxCheck$DFW_max[1] + 0.1 
  } else { 
  upperLimit <- 0.5 
  }
# sorts by number of students in each category for factoring purposes
  b4maxCheck %>%
  arrange(desc(students)) -> sorted_d1
sorted_d1 %>%
    pull(intersection) -> cat_sorted
  sorted_d1 %>%
  mutate(cat_factors = factor(intersection, levels = cat_sorted)) %>%
#Plotting code starts here:
  ggplot(aes(x = DFW, y = course, size = students, fill = intersection)) + 
  theme_classic() +
      geom_segment_interactive(aes(x = DFW_min, xend = DFW_max, yend=course, tooltip = paste(
    course,"\r",
    intersection,"\r",
    "Percentage Points Gap:",percent(DFW_max - DFW_min, accuracy = 0.1),"\r",
    "Grade Ratio:",round(DFW_max/DFW_min, digits = 2),"\r",
    "Students in Gap:",round(students_in_gap, digits = 1),"\r",
    "Total Enrollments:",total_enrollment,"\r"
    )), colour = "gray", linewidth = 15) +
  scale_size(range = c(5,15), guide = "none") +
  geom_point_interactive(aes(size = students, tooltip = paste0(
    course,"\r",
    intersection," (",percent(diversity,accuracy = 0.1)," of students)\r",
    DFW_students," of ",students," enrollments\r",
    percent(DFW, accuracy = 0.1)," DFW" )) , shape = 21) +
  scale_x_continuous(labels = scales::percent, limits = c(0,upperLimit)) +
  guides(fill = guide_legend(override.aes = list(size = 5), title="")) +
    labs(y = "")-> plot
  
  #Creates title in Markdown format
  cat('\n##', pairTitle , '\n')
  #prints interactive visualization
  print(htmltools::tagList(girafe(ggobj = plot)))
  #prints table
  print(table)
  
}
```



































```{r, include=FALSE, warning=FALSE}
library(ggiraph)
library(scales)
```

<br><br><br><br><br>

<!-- # DFW Rate Visualizations for `r d1$course[1]` -->


```{r, results='asis', include=FALSE, echo=FALSE, fig.height=4}
for (i in keptCols) { 
d1 %>%
  group_by(course, !!sym(i)) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), students = n(), DFW_students=sum(ABCDFW == "DFW"), .groups = "drop" ) %>%
  group_by(course) %>%
  mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
  mutate(students_in_gap = students[which.max(DFW)]*(max(DFW)-min(DFW)), diversity = students/sum(students), total_enrollment =      sum(students) ) -> b4maxCheck
  
  
if (b4maxCheck$DFW_max[1] > 0.5) {
  upperLimit <- b4maxCheck$DFW_max[1] + 0.1 
} else {
    upperLimit <- 0.5
    }
  
  b4maxCheck %>%
  arrange(desc(students)) -> sorted_d1
  
  sorted_d1 %>%
    pull(!!sym(i)) -> cat_sorted
    
  sorted_d1 %>%
  mutate(cat_factors = factor(!!sym(i), levels = cat_sorted)) %>%
  
  ggplot(aes(x = DFW, y = course, fill = cat_factors)) +
  theme_classic() +
  geom_segment_interactive(aes(x = DFW_min, xend = DFW_max, yend=course, tooltip = paste(
    course,"\r",
    !!sym(i),"\r",
    "Percentage Points Gap:",percent(DFW_max - DFW_min, accuracy = 0.1),"\r",
    "Grade Ratio:",round(DFW_max/DFW_min, digits = 2),"\r",
    "Students in Gap:",round(students_in_gap, digits = 1),"\r",
    "Total Enrollments:",total_enrollment,"\r"
    )), colour = "gray", linewidth = 15) +
  scale_size(range = c(5,15), guide = "none") +
  geom_point_interactive(aes(size = students, tooltip = paste0(
    course,"\r",
    !!sym(i)," (",percent(diversity,accuracy = 0.1)," of students)\r",
    DFW_students," of ",students," enrollments\r",
    percent(DFW, accuracy = 0.1)," DFW" )) , shape = 21) +
  scale_x_continuous(labels = scales::percent, limits = c(0,upperLimit)) +
  guides(fill = guide_legend(override.aes = list(size = 10), title="")) +
  labs(fill = sym(i), y = "") -> plot
  
cat('\n##', i , '\n')

print(htmltools::tagList(girafe(ggobj = plot))) # Use htmltools::tagList() to generate multiple interactive plots
                                                # results = 'asis' must go in {}
cat('\n')
}
```

<br><br><br><br><br>

<!-- # DFW Rate Intersectionality Visualizations for `r d1$course[1]` -->

```{r, results='asis', include=FALSE, echo=FALSE, warning=FALSE}

for (i in seq(from = 1, to = length(keptColsInt), by=2)) {
  pair <- c(keptColsInt[i], keptColsInt[i+1]) 
  pairTitle <- paste(keptColsInt[i],"&",keptColsInt[i+1])
d1 %>%
    group_by(course, !!sym(pair[1]), !!sym(pair[2])) %>%
    summarize(DFW = sum(ABCDFW == "DFW")/n(), students=n(), DFW_students=sum(ABCDFW == "DFW"), .groups = "drop" ) %>%
    mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
    mutate(intersection = paste(!!sym(pair[1]),!!sym(pair[2]), sep = "-")) %>%
  mutate(students_in_gap = students[which.max(DFW)]*(max(DFW)-min(DFW)), diversity = students/sum(students), total_enrollment =      sum(students) ) -> b4maxCheck
if (b4maxCheck$DFW_max[1] > 0.5) {
  upperLimit <- b4maxCheck$DFW_max[1] + 0.1 
  } else { 
  upperLimit <- 0.5 
 }
  b4maxCheck %>%
  arrange(desc(students)) -> sorted_d1
sorted_d1 %>%
    pull(intersection) -> cat_sorted
  sorted_d1 %>%
  mutate(cat_factors = factor(intersection, levels = cat_sorted)) %>%
  ggplot(aes(x = DFW, y = course, size = students, fill = intersection)) + 
  theme_classic() +
    
    
      geom_segment_interactive(aes(x = DFW_min, xend = DFW_max, yend=course, tooltip = paste(
    course,"\r",
    intersection,"\r",
    "Percentage Points Gap:",percent(DFW_max - DFW_min, accuracy = 0.1),"\r",
    "Grade Ratio:",round(DFW_max/DFW_min, digits = 2),"\r",
    "Students in Gap:",round(students_in_gap, digits = 1),"\r",
    "Total Enrollments:",total_enrollment,"\r"
    )), colour = "gray", linewidth = 15) +
  scale_size(range = c(5,15), guide = "none") +
  geom_point_interactive(aes(size = students, tooltip = paste0(
    course,"\r",
    intersection," (",percent(diversity,accuracy = 0.1)," of students)\r",
    DFW_students," of ",students," enrollments\r",
    percent(DFW, accuracy = 0.1)," DFW" )) , shape = 21) +

  scale_x_continuous(labels = scales::percent, limits = c(0,upperLimit)) +
  guides(fill = guide_legend(override.aes = list(size = 5), title="")) -> plot
  
    cat('\n##', pairTitle , '\n')
  
  print(htmltools::tagList(girafe(ggobj = plot)))
  
  cat('\n')
}
```



























```{r, include=FALSE}
# Original Code starts here
## Create Tables
# Simple code to examine a metric
dt %>%
  group_by(course,gender) %>%
  summarize(mean_gpa = mean(grade_point,na.rm=TRUE), count=n(), DFWcount = sum(ABCDFW == "DFW"),DFW = sum(ABCDFW == "DFW")/n(), .groups = "drop")

```


```{r, include=FALSE}
# More elaborate code to rearrange table and calculate gap in percentage points
dt %>%
  group_by(course,gender) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), .groups = "drop" ) %>%
  pivot_wider(names_from = gender, values_from=DFW) %>%
  group_by(course) %>%
  mutate(Gap = max(across(!matches("course"))) - min(across(!matches("course"))))

```

```{r, include=FALSE}
# Format into a table
dt %>%
  group_by(course,gender) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), .groups = "drop" ) %>%
  pivot_wider(names_from = gender, values_from=DFW) %>%
  group_by(course) %>%
  mutate(Gap = max(across(!matches("course"))) - min(across(!matches("course")))) %>%
  relocate(Gap, .after = "course") %>%
  ungroup() %>%
  gt(rowname_col = "course") %>%
  fmt_percent(
    decimals = 1
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = c(Gap))
  )%>%
  tab_header(title = "DFW")
```


<p>&nbsp;</p>


```{r, include=FALSE}
#Intersectionality table with renamed labels and polished formatting
dt %>%
  group_by(course,gender,firstgen) %>%
  mutate(firstgen = if_else(firstgen == "Y", "First", "Continuing")) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), .groups = "drop" ) %>%
  pivot_wider(names_from = c(gender,firstgen), values_from=DFW) %>%
  group_by(course) %>%
  mutate(Gap = max(across(!matches("course"))) - min(across(!matches("course")))) %>%
  relocate(Gap, .after = "course") %>%
  ungroup()%>%
  gt(rowname_col = "course") %>%
  fmt_percent( 
    decimals = 1
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = Gap)) %>%
  tab_spanner_delim(delim="_") %>%
    tab_header(title = "DFW")
```

<p>&nbsp;</p>

```{r, echo=FALSE, include=FALSE}
## Create Figures
#This illustrates how we are going to rearrange the data to prepare it for plotting
dt %>%
  group_by(course,firstgen) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), students = n(), .groups = "drop" ) %>%
  group_by(course) %>%
  mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
  mutate(firstgen = if_else(firstgen == "Y", "FirstGen", "Continuing"))
```


```{r, echo=FALSE, include=FALSE}
#Dress it up into plot
dt %>%
  group_by(course,firstgen) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), students = n(), .groups = "drop" ) %>%
  group_by(course) %>%
  mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
  mutate(firstgen = if_else(firstgen == "Y", "FirstGen", "Continuing")) %>%
  ggplot(aes(x = DFW, y = course, fill = firstgen)) + #plotting code starts here
  theme_classic() +
  geom_segment(aes(x = DFW_min, xend = DFW_max, yend=course),colour = "gray", linewidth = 15) +
  scale_size(range = c(5,15), guide = "none") + #use range to set min and max size of circles
  geom_point(aes(size = students),shape = 21) +
  scale_x_continuous(labels = scales::percent, limits = c(0,1)) +
  guides(fill = guide_legend(override.aes = list(size = 10))) +
  labs(fill = "Generation", y = "Course")
```


```{r, include=FALSE}
#Create interactive tooltips, i.e. mouseovers, using ggiraph library
library(ggiraph)
library(scales) #used for percent formatting
```


```{r, include=FALSE}
# Note, this may not display correctly in R, but should work when knit into an html
dt %>%
  group_by(course,firstgen) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), students = n(), DFW_students=sum(ABCDFW == "DFW"), .groups = "drop" ) %>% #added line to store DFW students explicitly
  group_by(course) %>%
  mutate(DFW_min = min(DFW), DFW_max = max(DFW)) %>% 
  mutate(students_in_gap = students[which.max(DFW)]*(max(DFW)-min(DFW)), diversity = students/sum(students), total_enrollment = sum(students) ) %>% #added students in gap calculation
  mutate(firstgen = if_else(firstgen == "Y", "FirstGen", "Continuing")) %>%
  ggplot(aes(x = DFW, y = course, fill = firstgen)) +
  theme_classic() +
  geom_segment_interactive(aes(x = DFW_min, xend = DFW_max, yend=course, tooltip = paste(
    course,"\r",
    firstgen,"\r",
    "Percentage Points Gap:",percent(DFW_max - DFW_min, accuracy = 0.1),"\r",
    "Grade Ratio:",round(DFW_max/DFW_min, digits = 2),"\r",
    "Students in Gap:",round(students_in_gap, digits = 1),"\r",
    "Total Enrollments:",total_enrollment,"\r"
    )),colour = "gray", linewidth = 15) + # change this to _interactive version in ggiraph and add tooltip code
  scale_size(range = c(5,15), guide = "none") + #use range to set min and max size of circles
  geom_point_interactive(aes(size = students, tooltip = paste0(
    course,"\r",
    firstgen," (",percent(diversity,accuracy = 0.1)," of students)\r",
    DFW_students," of ",students," enrollments\r",
    percent(DFW, accuracy = 0.1)," DFW"
    )),shape = 21) + # change this to _interactive version in ggiraph and add tooltip code
  scale_x_continuous(labels = scales::percent, limits = c(0,1)) +
  guides(fill = guide_legend(override.aes = list(size = 10))) +
  labs(fill = "Generation", y = "Course") ->p

girafe(ggobj=p)
```


```{r, include=FALSE}
dt %>%
  filter(course == "Calc1") %>%
  group_by(course,semester,firstgen) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), students = n(), .groups = "drop" ) %>%
  group_by(course, semester) %>%
  mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
  mutate(firstgen = if_else(firstgen == "Y", "FirstGen", "Continuing")) %>%
  ggplot(aes(x = semester, y = DFW, size = students, fill = firstgen)) + #plotting code starts here
  theme_classic() +
  geom_linerange(aes(ymin = DFW_min, ymax = DFW_max), colour = "grey", linewidth = 10) +
  scale_size(range = c(5,15), guide = "none") + #use range to set min and max size of circles
  geom_point(shape = 21) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  guides(fill = guide_legend(override.aes = list(size = 10))) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1)) +
  labs(fill = "Generation", x = "Semester")
```


```{r, include=FALSE}
dt %>%
  group_by(course,gender, firstgen) %>%
  summarize( DFW = sum(ABCDFW == "DFW")/n(), students = n(), .groups = "drop" ) %>%
  group_by(course) %>%
  mutate(DFW_min = min(DFW), DFW_max = max(DFW) ) %>%
  mutate(firstgen = if_else(firstgen == "Y", "FirstGen", "Continuing")) %>%
  mutate(intersection = paste(gender,firstgen, sep = "-")) %>%
  ggplot(aes(x = DFW, y = course, size = students, fill = intersection)) + #plotting code starts here
  theme_classic() +
  geom_linerange(aes(xmin = DFW_min, xmax = DFW_max), colour = "grey", linewidth = 15) + #coordinate linewidth with max size of circles
  scale_size(range = c(2,15), guide = "none") + #use range to set min and max size of circles
  geom_point(shape = 21, alpha = 0.49) +
  scale_x_continuous(labels = scales::percent, limits = c(0,1)) +
  guides(fill = guide_legend(override.aes = list(size = 10))) + 
  labs(fill = "Gender-Generation", y = "Course")
```
